# 使用轻量级 JDK 镜像
FROM openjdk:11-jdk-slim

# 创建 app 目录
WORKDIR /app

# 将打包好的 jar 拷贝进容器（确保路径正确）
COPY target/sky-server-1.0-SNAPSHOT.jar app.jar

# 开放端口
EXPOSE 8080

# 启动应用
ENTRYPOINT ["java", "-jar", "app.jar"]
